### Librerias necesarias para llevar acabo la actividad

In [33]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


### Imports necesarios para la actividad

In [34]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim

### Cargamos el archivo

En nuestro caso el dataset tiene solo 2 columnas, la salida hamm o spam y el mensaje

In [35]:
import numpy as np

#utilizamos el comando skiprows para que el modelo no coja la primera fila que es la cabezera
dataset = np.loadtxt('Datasets/lie_dataset_100.csv', delimiter=',', skiprows=1)
X = dataset[:, 0:4]
y = dataset[:, 4]
print(X[0:5])
print(y[0:5])

[[  3.86  80.    64.    62.  ]
 [  2.41  62.    16.    35.  ]
 [  1.72  66.    39.     1.  ]
 [  2.28 103.    78.    79.  ]
 [  3.39  83.     5.    21.  ]]
[1. 0. 0. 1. 0.]


### Tranformación de los datos

Tenemos que transformar los datos ya que PyTorch y NumPy utilizan puntos flotantes diferentes

In [24]:
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y.reshape(-1, 1), dtype=torch.float32)

print(X[0:5])
print(y[0:5])


tensor([[  3.8600,  80.0000,  64.0000,  62.0000],
        [  2.4100,  62.0000,  16.0000,  35.0000],
        [  1.7200,  66.0000,  39.0000,   1.0000],
        [  2.2800, 103.0000,  78.0000,  79.0000],
        [  3.3900,  83.0000,   5.0000,  21.0000]])
tensor([[1.],
        [0.],
        [0.],
        [1.],
        [0.]])


### Definimos el modelo

In [25]:
model = nn.Sequential(
    nn.Linear(4, 8),    # 4 features de entrada, capa oculta de 8
    nn.ReLU(),
    nn.Linear(8, 4),    # reducimos a 4
    nn.ReLU(),
    nn.Linear(4, 1),    # salida binaria (lie o no lie)
    nn.Sigmoid()
)
print(model)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=4, bias=True)
  (3): ReLU()
  (4): Linear(in_features=4, out_features=1, bias=True)
  (5): Sigmoid()
)


### Funcion de perdida

In [26]:
loss_fn = nn.BCELoss() #al ser clasificación binaria establecemos binary cross entropy
optimizer = optim.Adam(model.parameters(), lr=0.001) #Necesita saber qué parámetros optimizar

### Entenamos el modelo

In [27]:
n_epochs = 500
batch_size = 10
num_samples = min(len(X), len(y)) # Use the minimum length to ensure X and y are always aligned

for epoch in range(n_epochs):
  for i in range(0, num_samples, batch_size):
    # Define the end index for the current batch, ensuring it doesn't exceed num_samples
    current_batch_end = min(i + batch_size, num_samples)
    Xbatch = X[i:current_batch_end] #Partición del conjunto de datos
    ybatch = y[i:current_batch_end] #Corresponding partition for labels

    # Skip if the batch is empty (e.g., if num_samples was 0 or due to an edge case)
    if Xbatch.shape[0] == 0:
      continue

    #Forward
    y_pred = model(Xbatch)
    loss = loss_fn(y_pred, ybatch) # Calculo la pérdida
    optimizer.zero_grad()
    loss.backward()
    optimizer.step() # Actualiza pesos
  print(f'Finished epoch {epoch}, latest loss {loss}')

Finished epoch 0, latest loss 0.7509045600891113
Finished epoch 1, latest loss 0.5122089385986328
Finished epoch 2, latest loss 0.41690921783447266
Finished epoch 3, latest loss 0.47201743721961975
Finished epoch 4, latest loss 0.4889691472053528
Finished epoch 5, latest loss 0.4415181279182434
Finished epoch 6, latest loss 0.40641728043556213
Finished epoch 7, latest loss 0.39163002371788025
Finished epoch 8, latest loss 0.3857685625553131
Finished epoch 9, latest loss 0.379863977432251
Finished epoch 10, latest loss 0.3705565333366394
Finished epoch 11, latest loss 0.3599418103694916
Finished epoch 12, latest loss 0.35053133964538574
Finished epoch 13, latest loss 0.34257611632347107
Finished epoch 14, latest loss 0.33542510867118835
Finished epoch 15, latest loss 0.3286193907260895
Finished epoch 16, latest loss 0.32220837473869324
Finished epoch 17, latest loss 0.3163122534751892
Finished epoch 18, latest loss 0.3109843134880066
Finished epoch 19, latest loss 0.30616310238838196
Fi

### Evaluamos el modelo

In [28]:
with torch.no_grad(): # para que no tenga en cuenta derivaciones anteriores
  y_pred = model(X)
  accuracy = (y_pred.round() == y).float().mean()
  print(f"Accuracy {accuracy}")

Accuracy 0.9599999785423279


In [29]:
# Sin no grad
y_pred = model(X)
accuracy = (y_pred.round() == y).float().mean()
print(f"Accuracy {accuracy}")

Accuracy 0.9599999785423279


### Hacer predicciones

In [30]:
prediction = model(X)
rounded = prediction.round()
print(rounded)

tensor([[1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
      

In [32]:
prediction = (model(X) > 0.5).int()
for i in range(10):
  print('%s --> %d (expected %d)' % (X[i].tolist(), prediction[i], y[i]))

[3.859999895095825, 80.0, 64.0, 62.0] --> 1 (expected 1)
[2.4100000858306885, 62.0, 16.0, 35.0] --> 0 (expected 0)
[1.7200000286102295, 66.0, 39.0, 1.0] --> 0 (expected 0)
[2.2799999713897705, 103.0, 78.0, 79.0] --> 1 (expected 1)
[3.390000104904175, 83.0, 5.0, 21.0] --> 0 (expected 0)
[2.4600000381469727, 66.0, 41.0, 25.0] --> 0 (expected 0)
[3.430000066757202, 93.0, 57.0, 64.0] --> 1 (expected 1)
[2.759999990463257, 69.0, 23.0, 25.0] --> 0 (expected 0)
[2.2799999713897705, 71.0, 20.0, 20.0] --> 0 (expected 0)
[3.4100000858306885, 96.0, 79.0, 73.0] --> 1 (expected 1)
